/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Condominio.java
 *
 * Created on 02/05/2009, 04:32:48
 */

package br.com.syndic.frame;

import br.com.syndic.controller.CondominioController;
import br.com.syndic.controller.CondominioDetalheController;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Albert Eije
 */
public class Condominio extends InternalFrame implements ActionListener {

    private Connection conn = null;

    /** Creates new form GridFrame2 */
    public Condominio(Connection conn, CondominioController controller) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControl1.setController(controller);
            gridControl1.setGridDataLocator(controller);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void reloadData() {
        gridControl1.reloadData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        exportButton1 = new org.openswing.swing.client.ExportButton();
        importButton1 = new org.openswing.swing.client.ImportButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        integerColumn1 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn8 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn9 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn10 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn11 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn12 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn13 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn14 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn15 = new org.openswing.swing.table.columns.client.TextColumn();
        decimalColumn1 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn2 = new org.openswing.swing.table.columns.client.DecimalColumn();
        decimalColumn3 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn16 = new org.openswing.swing.table.columns.client.TextColumn();

        setTitle("Cadastro de Condomínios");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Condomínios");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        insertButton1.addActionListener(this);
        jPanel2.add(insertButton1);
        jPanel2.add(editButton1);
        jPanel2.add(deleteButton1);
        jPanel2.add(reloadButton1);
        jPanel2.add(exportButton1);
        jPanel2.add(importButton1);
        jPanel2.add(navigatorBar1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setEditButton(editButton1);
        gridControl1.setExportButton(exportButton1);
        gridControl1.setFunctionId("condominio");
        gridControl1.setImportButton(importButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl1.setValueObjectClassName("br.com.syndic.vo.CondominioVO");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        integerColumn1.setColumnName("codCondominio");
        integerColumn1.setColumnSortable(true);
        integerColumn1.setHeaderColumnName("Código Condomínio");
        integerColumn1.setSortVersus(org.openswing.swing.util.java.Consts.ASC_SORTED);
        gridControl1.getColumnContainer().add(integerColumn1);

        textColumn1.setColumnName("nomeCondominio");
        textColumn1.setColumnSortable(true);
        textColumn1.setHeaderColumnName("Nome do Condomínio");
        textColumn1.setPreferredWidth(250);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnFilterable(true);
        textColumn2.setColumnName("enderecoCondominio");
        textColumn2.setHeaderColumnName("Endereço Condomínio");
        textColumn2.setPreferredWidth(250);
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn3.setColumnName("bairroCondominio");
        textColumn3.setColumnRequired(false);
        textColumn3.setHeaderColumnName("Bairro");
        textColumn3.setMaxCharacters(50);
        gridControl1.getColumnContainer().add(textColumn3);

        textColumn4.setColumnName("cidadeCondominio");
        textColumn4.setHeaderColumnName("Cidade");
        gridControl1.getColumnContainer().add(textColumn4);

        textColumn5.setColumnName("ufCondominio");
        textColumn5.setHeaderColumnName("Estado");
        textColumn5.setPreferredWidth(50);
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnName("cepCondominio");
        textColumn6.setHeaderColumnName("CEP");
        gridControl1.getColumnContainer().add(textColumn6);

        textColumn7.setColumnName("foneCondominio");
        textColumn7.setHeaderColumnName("Fone");
        gridControl1.getColumnContainer().add(textColumn7);

        textColumn8.setColumnName("faxCondominio");
        textColumn8.setHeaderColumnName("Fax");
        gridControl1.getColumnContainer().add(textColumn8);

        textColumn9.setColumnName("cnpjCondominio");
        textColumn9.setHeaderColumnName("CNPJ");
        gridControl1.getColumnContainer().add(textColumn9);

        textColumn10.setColumnName("emailCondominio");
        textColumn10.setHeaderColumnName("e-mail");
        textColumn10.setPreferredWidth(250);
        gridControl1.getColumnContainer().add(textColumn10);

        textColumn11.setColumnName("sindicoCondominio");
        textColumn11.setHeaderColumnName("Síndico");
        gridControl1.getColumnContainer().add(textColumn11);

        textColumn12.setColumnName("instrucao1");
        gridControl1.getColumnContainer().add(textColumn12);

        textColumn13.setColumnName("instrucao2");
        gridControl1.getColumnContainer().add(textColumn13);

        textColumn14.setColumnName("instrucao3");
        gridControl1.getColumnContainer().add(textColumn14);

        textColumn15.setColumnName("instrucao4");
        gridControl1.getColumnContainer().add(textColumn15);

        decimalColumn1.setColumnName("moraCondominio");
        decimalColumn1.setDecimals(2);
        decimalColumn1.setHeaderColumnName("Mora");
        gridControl1.getColumnContainer().add(decimalColumn1);

        decimalColumn2.setColumnName("multaCondominio");
        decimalColumn2.setDecimals(2);
        decimalColumn2.setHeaderColumnName("Multa");
        gridControl1.getColumnContainer().add(decimalColumn2);

        decimalColumn3.setColumnName("rateioCondominio");
        decimalColumn3.setDecimals(2);
        decimalColumn3.setHeaderColumnName("Rateio");
        gridControl1.getColumnContainer().add(decimalColumn3);

        textColumn16.setColumnName("diaVencimento");
        textColumn16.setHeaderColumnName("Dia vencimento");
        textColumn16.setTextAlignment(SwingConstants.RIGHT);
        gridControl1.getColumnContainer().add(textColumn16);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == insertButton1) {
            Condominio.this.insertButton1ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        new CondominioDetalheController(this, null, conn);
    }//GEN-LAST:event_insertButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn1;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn2;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn3;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.client.ExportButton exportButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.ImportButton importButton1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn10;
    private org.openswing.swing.table.columns.client.TextColumn textColumn11;
    private org.openswing.swing.table.columns.client.TextColumn textColumn12;
    private org.openswing.swing.table.columns.client.TextColumn textColumn13;
    private org.openswing.swing.table.columns.client.TextColumn textColumn14;
    private org.openswing.swing.table.columns.client.TextColumn textColumn15;
    private org.openswing.swing.table.columns.client.TextColumn textColumn16;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    private org.openswing.swing.table.columns.client.TextColumn textColumn8;
    private org.openswing.swing.table.columns.client.TextColumn textColumn9;
    // End of variables declaration//GEN-END:variables

}
