/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Banco.java
 *
 * Created on 02/05/2009, 04:32:48
 */

package br.com.syndic.frame;

import br.com.syndic.controller.InquilinoController;
import br.com.syndic.controller.InquilinoDetalheController;
import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.ListSelectionModel;
import org.openswing.swing.mdi.client.InternalFrame;

/**
 *
 * @author Albert Eije
 */
public class Inquilino extends InternalFrame implements ActionListener {

    private Connection conn = null;

    /** Creates new form GridFrame2 */
    public Inquilino(Connection conn, InquilinoController controller) {
        this.conn = conn;
        try {
            initComponents();
            setSize(750, 300);
            gridControl1.setController(controller);
            gridControl1.setGridDataLocator(controller);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void reloadData() {
        gridControl1.reloadData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        insertButton1 = new org.openswing.swing.client.InsertButton();
        editButton1 = new org.openswing.swing.client.EditButton();
        deleteButton1 = new org.openswing.swing.client.DeleteButton();
        reloadButton1 = new org.openswing.swing.client.ReloadButton();
        exportButton1 = new org.openswing.swing.client.ExportButton();
        importButton1 = new org.openswing.swing.client.ImportButton();
        navigatorBar1 = new org.openswing.swing.client.NavigatorBar();
        gridControl1 = new org.openswing.swing.client.GridControl();
        textColumn9 = new org.openswing.swing.table.columns.client.TextColumn();
        integerColumn2 = new org.openswing.swing.table.columns.client.IntegerColumn();
        textColumn1 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn2 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn3 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn4 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn5 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn6 = new org.openswing.swing.table.columns.client.TextColumn();
        textColumn7 = new org.openswing.swing.table.columns.client.TextColumn();
        currencyColumn1 = new org.openswing.swing.table.columns.client.CurrencyColumn();
        decimalColumn1 = new org.openswing.swing.table.columns.client.DecimalColumn();
        textColumn8 = new org.openswing.swing.table.columns.client.TextColumn();

        setTitle("Cadastro de Inquilinos");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setText("Cadastro de Inquilinos");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        insertButton1.addActionListener(this);
        jPanel2.add(insertButton1);
        jPanel2.add(editButton1);
        jPanel2.add(deleteButton1);
        jPanel2.add(reloadButton1);
        jPanel2.add(exportButton1);
        jPanel2.add(importButton1);
        jPanel2.add(navigatorBar1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        gridControl1.setDeleteButton(deleteButton1);
        gridControl1.setExportButton(exportButton1);
        gridControl1.setFunctionId("inquilino");
        gridControl1.setImportButton(importButton1);
        gridControl1.setNavBar(navigatorBar1);
        gridControl1.setReloadButton(reloadButton1);
        gridControl1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        gridControl1.setValueObjectClassName("br.com.syndic.vo.InquilinoVO");
        gridControl1.getColumnContainer().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        textColumn9.setColumnName("codInquilino");
        textColumn9.setHeaderColumnName("Código Inquilino");
        gridControl1.getColumnContainer().add(textColumn9);

        integerColumn2.setColumnName("codCondominio");
        integerColumn2.setColumnSortable(true);
        integerColumn2.setHeaderColumnName("Condominio");
        gridControl1.getColumnContainer().add(integerColumn2);

        textColumn1.setColumnFilterable(true);
        textColumn1.setColumnName("nomeCondominio");
        textColumn1.setColumnSortable(true);
        textColumn1.setHeaderColumnName("Nome do Condomínio");
        textColumn1.setPreferredWidth(250);
        gridControl1.getColumnContainer().add(textColumn1);

        textColumn2.setColumnName("apto");
        gridControl1.getColumnContainer().add(textColumn2);

        textColumn3.setColumnName("bloco");
        gridControl1.getColumnContainer().add(textColumn3);

        textColumn4.setColumnName("quadra");
        gridControl1.getColumnContainer().add(textColumn4);

        textColumn5.setColumnName("nomeInquilino");
        gridControl1.getColumnContainer().add(textColumn5);

        textColumn6.setColumnName("foneInquilino");
        gridControl1.getColumnContainer().add(textColumn6);

        textColumn7.setColumnName("celularInquilino");
        gridControl1.getColumnContainer().add(textColumn7);

        currencyColumn1.setColumnName("cotaNormal");
        gridControl1.getColumnContainer().add(currencyColumn1);

        decimalColumn1.setColumnName("fracaoIdeal");
        gridControl1.getColumnContainer().add(decimalColumn1);

        textColumn8.setColumnName("cpfInquilino");
        gridControl1.getColumnContainer().add(textColumn8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(gridControl1, gridBagConstraints);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == insertButton1) {
            Inquilino.this.insertButton1ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        new InquilinoDetalheController(this, null, conn);
    }//GEN-LAST:event_insertButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.openswing.swing.table.columns.client.CurrencyColumn currencyColumn1;
    private org.openswing.swing.table.columns.client.DecimalColumn decimalColumn1;
    private org.openswing.swing.client.DeleteButton deleteButton1;
    private org.openswing.swing.client.EditButton editButton1;
    private org.openswing.swing.client.ExportButton exportButton1;
    private org.openswing.swing.client.GridControl gridControl1;
    private org.openswing.swing.client.ImportButton importButton1;
    private org.openswing.swing.client.InsertButton insertButton1;
    private org.openswing.swing.table.columns.client.IntegerColumn integerColumn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.openswing.swing.client.NavigatorBar navigatorBar1;
    private org.openswing.swing.client.ReloadButton reloadButton1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn1;
    private org.openswing.swing.table.columns.client.TextColumn textColumn2;
    private org.openswing.swing.table.columns.client.TextColumn textColumn3;
    private org.openswing.swing.table.columns.client.TextColumn textColumn4;
    private org.openswing.swing.table.columns.client.TextColumn textColumn5;
    private org.openswing.swing.table.columns.client.TextColumn textColumn6;
    private org.openswing.swing.table.columns.client.TextColumn textColumn7;
    private org.openswing.swing.table.columns.client.TextColumn textColumn8;
    private org.openswing.swing.table.columns.client.TextColumn textColumn9;
    // End of variables declaration//GEN-END:variables

}
